In [ ]:
!pip install pandas

In [3]:
import pandas as pd

# Series

In [4]:
lst =[1,2,3,34,4,5,3,23]

In [5]:
ser = pd.Series([4,4,5,3,23])
ser

0     4
1     4
2     5
3     3
4    23
dtype: int64

In [6]:
type(ser)

pandas.core.series.Series

In [7]:
ser = pd.Series([4,4,5,3,23],name='series')
ser

0     4
1     4
2     5
3     3
4    23
Name: series, dtype: int64

In [6]:
ser = pd.Series([4,4,5,3,23],name='series',index=['a','b','c','d','e'])
ser

a     4
b     4
c     5
d     3
e    23
Name: series, dtype: int64

# Data Frame

## Using List

In [7]:
lst = [['apple',5],['banana',6],['mango',7]]
pd.DataFrame(lst)

        0  1
0   apple  5
1  banana  6
2   mango  7

In [8]:
pd.DataFrame(lst, columns=['Fruits','Quantitues'])   #Naming of columns

   Fruits  Quantitues
0   apple           5
1  banana           6
2   mango           7

In [9]:
lst = [['apple',5,10],['banana',6,20],['mango',7,30],['orange',8,20]]  #adding another column and row
p = pd.DataFrame(lst, columns=['Fruits','Quantitues','Price']) #need to add column name if not error will occur
p

   Fruits  Quantitues  Price
0   apple           5     10
1  banana           6     20
2   mango           7     30
3  orange           8     20

## Using Dictionary

In [10]:
dic = {
    'Fruits' : ['apple','banana','mango','orange'],
    'Quantity' : [5,6,7,8],
    'Price' : [10,20,30,20]
}
dic

{'Fruits': ['apple', 'banana', 'mango', 'orange'],
 'Quantity': [5, 6, 7, 8],
 'Price': [10, 20, 30, 20]}

In [11]:
df = pd.DataFrame(dic)
df

   Fruits  Quantity  Price
0   apple         5     10
1  banana         6     20
2   mango         7     30
3  orange         8     20

## Accesing the Columns

In [12]:
df

   Fruits  Quantity  Price
0   apple         5     10
1  banana         6     20
2   mango         7     30
3  orange         8     20

In [13]:
df['Fruits']

0     apple
1    banana
2     mango
3    orange
Name: Fruits, dtype: object

In [14]:
df['Fruits'].ndim  #Dimension OF This Columns (and this is in series format because we are only calling one column )

1

In [17]:
df['Fruits'].shape # It shows number of element

(4,)

In [19]:
df[['Fruits','Quantity']]

   Fruits  Quantity
0   apple         5
1  banana         6
2   mango         7
3  orange         8

In [20]:
df[['Fruits','Quantity']].ndim  # Access 2 columns means it became 2d arry

2

In [21]:
df[['Fruits','Quantity']].shape  # 4 rows and 2 columns

(4, 2)

In [23]:
df[['Fruits','Quantity','Price']] # Accessing 3 Columns

   Fruits  Quantity  Price
0   apple         5     10
1  banana         6     20
2   mango         7     30
3  orange         8     20

In [29]:
df['Like/Dislike'] = ['L','D','L','L'] # To Add new Column, note: make sure to pass no of values = Rows
df

   Fruits  Quantity  Price Like/Dislike
0   apple         5     10            L
1  banana         6     20            D
2   mango         7     30            L
3  orange         8     20            L

## Arthimetic Operations

In [25]:
d = pd.DataFrame({'A':[1,2,3,4,5],'B':[6,7,8,9,10]})
d

   A   B
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

In [33]:
d['C'] = d['A'] + d['B']

In [34]:
d

   A   B   c   C
0  1   6   7   7
1  2   7   9   9
2  3   8  11  11
3  4   9  13  13
4  5  10  15  15

In [38]:
d['D'] = d['A'] * d['c']

In [39]:
d

   A   B   c   C   D
0  1   6   7   6   7
1  2   7   9  14  18
2  3   8  11  24  33
3  4   9  13  36  52
4  5  10  15  50  75

## Insert An Column

In [40]:
d

   A   B   c   C   D
0  1   6   7   6   7
1  2   7   9  14  18
2  3   8  11  24  33
3  4   9  13  36  52
4  5  10  15  50  75

In [ ]:
d.insert(0,'Alpha',['a','b','c','d','e'])   # you can insert any column at any place u want

In [44]:
d

  Alpha  A   B   c   C   D
0     a  1   6   7   6   7
1     b  2   7   9  14  18
2     c  3   8  11  24  33
3     d  4   9  13  36  52
4     e  5  10  15  50  75

In [46]:
d.insert(3,'A*b',(d['A']*d['B']))

In [47]:
d

  Alpha  A   B  A*b   c   C   D
0     a  1   6    6   7   6   7
1     b  2   7   14   9  14  18
2     c  3   8   24  11  24  33
3     d  4   9   36  13  36  52
4     e  5  10   50  15  50  75

## Delete An Column

In [48]:
del d['c']   # To delete a single column

In [49]:
d

  Alpha  A   B  A*b   C   D
0     a  1   6    6   6   7
1     b  2   7   14  14  18
2     c  3   8   24  24  33
3     d  4   9   36  36  52
4     e  5  10   50  50  75

In [ ]:
del d    # To delete whole data permanently

In [ ]:
d

# Load the Dataset

In [ ]:
df = pd.read('file_name that is in your folder')

In [4]:
df = pd.read_csv('petrol_consumption.csv') # csv means comma seperated value

In [5]:
df

,Petrol_tax,Average_income,Paved_Highways,Population_Driver_licence(%),Petrol_Consumption
0,9.00,3571,1976,0.525,541
1,9.00,4092,1250,0.572,524
2,9.00,3865,1586,0.580,561
3,7.50,4870,2351,0.529,414
4,8.00,4399,431,0.544,410
5,10.00,5342,1333,0.571,457
6,8.00,5319,11868,0.451,344
7,8.00,5126,2138,0.553,467
8,8.00,4447,8577,0.529,464
9,7.00,4512,8507,0.552,498
10,8.00,4391,5939,0.530,580
11,7.50,5126,14186,0.525,471
12,7.00,4817,6930,0.574,525
13,7.00,4207,6580,0.545,508
14,7.00,4332,8159,0.608,566
15,7.00,4318,10340,0.586,635
16,7.00,4206,8508,0.572,603
17,7.00,3718,4725,0.540,714
18,7.00,4716,5915,0.724,865
19,8.50,4341,6010,0.677,640
20,7.00,4593,7834,0.663,649
21,8.00,4983,602,0.602,540
22,9.00,4897,2449,0.511,464
23,9.00,4258,4686,0.517,547
24,8.50,4574,2619,0.551,460
25,9.00,3721,4746,0.544,566
26,8.00,3448,5399,0.548,577
27,7.50,3846,9061,0.579,631
28,8.00,4188,5975,0.563,574
29,9.00,3601,4650,0.493,534
30,7.00,3640,6905,0.518,571
31,7.00,3333,6594,0.513,554
32,8.00,3063,6524,0.578,577
33,7.50,3357,4121,0.547,628
34,8.00,3528,3495,0.487,487
35,6.58,3802,7834,0.629,644
36,5.00,4045,17782,0.566,640
37,7.00,3897,6385,0.586,704
38,8.50,3635,3274,0.663,648
39,7.00,4345,3905,0.672,968
40,7.00,4449,4639,0.626,587
41,7.00,3656,3985,0.563,699
42,7.00,4300,3635,0.603,632
43,7.00,3745,2611,0.508,591
44,6.00,5215,2302,0.672,782
45,9.00,4476,3942,0.571,510
46,7.00,4296,4083,0.623,610
47,7.00,5002,9794,0.593,524

## Basic EDA

In [7]:
df.ndim

2

In [6]:
df.shape

(48, 5)

In [9]:
df.columns  # TO view columns names

Index(['Petrol_tax', 'Average_income', 'Paved_Highways',
       'Population_Driver_licence(%)', 'Petrol_Consumption'],
      dtype='object')

In [10]:
df.head()    # Use to find top 5 values

,Petrol_tax,Average_income,Paved_Highways,Population_Driver_licence(%),Petrol_Consumption
0,9.0,3571,1976,0.525,541
1,9.0,4092,1250,0.572,524
2,9.0,3865,1586,0.580,561
3,7.5,4870,2351,0.529,414
4,8.0,4399,431,0.544,410

In [11]:
df.head(2)    # Use to find top 2 values

,Petrol_tax,Average_income,Paved_Highways,Population_Driver_licence(%),Petrol_Consumption
0,9.0,3571,1976,0.525,541
1,9.0,4092,1250,0.572,524

In [12]:
df.tail()    # Use to find bottom 5 values

,Petrol_tax,Average_income,Paved_Highways,Population_Driver_licence(%),Petrol_Consumption
43,7.0,3745,2611,0.508,591
44,6.0,5215,2302,0.672,782
45,9.0,4476,3942,0.571,510
46,7.0,4296,4083,0.623,610
47,7.0,5002,9794,0.593,524

In [13]:
df.info()   # Use to find intire information about data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 5 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Petrol_tax                    48 non-null     float64
 1   Average_income                48 non-null     int64
 2   Paved_Highways                48 non-null     int64
 3   Population_Driver_licence(%)  48 non-null     float64
 4   Petrol_Consumption            48 non-null     int64
dtypes: float64(2), int64(3)
memory usage: 2.0 KB

In [15]:
df.describe()   # Use to find (count, mean, standard deviation and count, etc)

,Petrol_tax,Average_income,Paved_Highways,Population_Driver_licence(%),Petrol_Consumption
count,48.000000,48.000000,48.000000,48.000000,48.000000
mean,7.668333,4241.833333,5565.416667,0.570333,576.770833
std,0.950770,573.623768,3491.507166,0.055470,111.885816
min,5.000000,3063.000000,431.000000,0.451000,344.000000
25%,7.000000,3739.000000,3110.250000,0.529750,509.500000
50%,7.500000,4298.000000,4735.500000,0.564500,568.500000
75%,8.125000,4578.750000,7156.000000,0.595250,632.750000
max,10.000000,5342.000000,17782.000000,0.724000,968.000000

## Indexing and Slicing - iloc[] and loc[]

In [16]:
df.head()

,Petrol_tax,Average_income,Paved_Highways,Population_Driver_licence(%),Petrol_Consumption
0,9.0,3571,1976,0.525,541
1,9.0,4092,1250,0.572,524
2,9.0,3865,1586,0.580,561
3,7.5,4870,2351,0.529,414
4,8.0,4399,431,0.544,410

In [17]:
df.iloc[3]

Petrol_tax                         7.500
Average_income                  4870.000
Paved_Highways                  2351.000
Population_Driver_licence(%)       0.529
Petrol_Consumption               414.000
Name: 3, dtype: float64

In [18]:
df.iloc[40]

Petrol_tax                         7.000
Average_income                  4449.000
Paved_Highways                  4639.000
Population_Driver_licence(%)       0.626
Petrol_Consumption               587.000
Name: 40, dtype: float64

****
# iloc[]

-  TO print specific rows and columns we use **data_name.iloc[0:3,0:6]**
    -  (0:3 means form **0th index** to **3-1 row** and 0:6 means from **0th to 6-1 columns**)
    -  You can use **'df.iloc[:3]'** this if you want all columns and only specific rows.
    -  You can use **'df.iloc[:,:3]'** this if you want all rows and only specific columns.
    -  **df.iloc[:3,0:6:2]** Using this you can skip 1 columns and fetch and agin skip 1 column

In [20]:
df.iloc[0:3,0:6]

,Petrol_tax,Average_income,Paved_Highways,Population_Driver_licence(%),Petrol_Consumption
0,9.0,3571,1976,0.525,541
1,9.0,4092,1250,0.572,524
2,9.0,3865,1586,0.580,561

In [25]:
df.iloc[:2,:3]

   Petrol_tax  Average_income  Paved_Highways
0         9.0            3571            1976
1         9.0            4092            1250

In [23]:
df.iloc[:3]

,Petrol_tax,Average_income,Paved_Highways,Population_Driver_licence(%),Petrol_Consumption
0,9.0,3571,1976,0.525,541
1,9.0,4092,1250,0.572,524
2,9.0,3865,1586,0.580,561

In [24]:
df.iloc[:4,0:6:2]

   Petrol_tax  Paved_Highways  Petrol_Consumption
0         9.0            1976                 541
1         9.0            1250                 524
2         9.0            1586                 561
3         7.5            2351                 414

In [26]:
df.iloc[:7:3,0:6:2]

   Petrol_tax  Paved_Highways  Petrol_Consumption
0         9.0            1976                 541
3         7.5            2351                 414
6         8.0           11868                 344

****
# loc[]

- How to use loc[]
    - Use to fetch only specific rows and columns
    - **df.loc[:3,['columns name to fetch in single code']]** This is the command
    - **Note**: In this function you dont't need to give index+1 value
        - for example: df.loc[:3], this will print values from 0th index to 3th index unlike other slicing methods.

In [28]:
df.loc[:3,['Petrol_tax','Paved_Highways']]

   Petrol_tax  Paved_Highways
0         9.0            1976
1         9.0            1250
2         9.0            1586
3         7.5            2351

In [29]:
df.loc[11:15,['Petrol_tax','Petrol_Consumption']]

    Petrol_tax  Petrol_Consumption
11         7.5                 471
12         7.0                 525
13         7.0                 508
14         7.0                 566
15         7.0                 635

# Unique Vlaues and Identification

In [30]:
df.head()

,Petrol_tax,Average_income,Paved_Highways,Population_Driver_licence(%),Petrol_Consumption
0,9.0,3571,1976,0.525,541
1,9.0,4092,1250,0.572,524
2,9.0,3865,1586,0.580,561
3,7.5,4870,2351,0.529,414
4,8.0,4399,431,0.544,410

In [31]:
df.nunique()   # to find how many unique values are there.

Petrol_tax                       9
Average_income                  47
Paved_Highways                  47
Population_Driver_licence(%)    39
Petrol_Consumption              43
dtype: int64

In [32]:
df['Petrol_tax'].unique()  # to view unique values

array([ 9.  ,  7.5 ,  8.  , 10.  ,  7.  ,  8.5 ,  6.58,  5.  ,  6.  ])

In [36]:
df['Petrol_tax'].value_counts()

Petrol_tax
7.00     19
8.00     10
9.00      8
7.50      4
8.50      3
10.00     1
6.58      1
5.00      1
6.00      1
Name: count, dtype: int64

In [40]:
df.isna()   # (df.isna() / df.null()) To find the missing value in data (true means missing)

,Petrol_tax,Average_income,Paved_Highways,Population_Driver_licence(%),Petrol_Consumption
0,False,False,False,False,False
1,False,False,False,False,False
2,False,False,False,False,False
3,False,False,False,False,False
4,False,False,False,False,False
5,False,False,False,False,False
6,False,False,False,False,False
7,False,False,False,False,False
8,False,False,False,False,False
9,False,False,False,False,False
10,False,False,False,False,False
11,False,False,False,False,False
12,False,False,False,False,False
13,False,False,False,False,False
14,False,False,False,False,False
15,False,False,False,False,False
16,False,False,False,False,False
17,False,False,False,False,False
18,False,False,False,False,False
19,False,False,False,False,False
20,False,False,False,False,False
21,False,False,False,False,False
22,False,False,False,False,False
23,False,False,False,False,False
24,False,False,False,False,False
25,False,False,False,False,False
26,False,False,False,False,False
27,False,False,False,False,False
28,False,False,False,False,False
29,False,False,False,False,False
30,False,False,False,False,False
31,False,False,False,False,False
32,False,False,False,False,False
33,False,False,False,False,False
34,False,False,False,False,False
35,False,False,False,False,False
36,False,False,False,False,False
37,False,False,False,False,False
38,False,False,False,False,False
39,False,False,False,False,False
40,False,False,False,False,False
41,False,False,False,False,False
42,False,False,False,False,False
43,False,False,False,False,False
44,False,False,False,False,False
45,False,False,False,False,False
46,False,False,False,False,False
47,False,False,False,False,False

In [43]:
df.isnull().any()  # Used to find missing value in a columns

Petrol_tax                      False
Average_income                  False
Paved_Highways                  False
Population_Driver_licence(%)    False
Petrol_Consumption              False
dtype: bool

In [45]:
df.isnull().sum()  # Used to find how many values are missing in a columns

Petrol_tax                      0
Average_income                  0
Paved_Highways                  0
Population_Driver_licence(%)    0
Petrol_Consumption              0
dtype: int64

# fillna() and dropna()

In [46]:
df.head()

,Petrol_tax,Average_income,Paved_Highways,Population_Driver_licence(%),Petrol_Consumption
0,9.0,3571,1976,0.525,541
1,9.0,4092,1250,0.572,524
2,9.0,3865,1586,0.580,561
3,7.5,4870,2351,0.529,414
4,8.0,4399,431,0.544,410

In [ ]:
df.fillna(4000) # not prefered changes mean median

In [ ]:
df['Average_income'].fillna(df['Average_income'].mean())  # this will not change data permanently

In [ ]:
df['Average_income'].fillna(df['Average_income'].mean(),inplace=True) # this will change data permanently

In [ ]:
df.dropna(inplace=True) # delete all null value rows ( even if any row has a single null value)

# Duplicate Data

In [58]:
df.duplicated().sum() # Used to find duplicate values in table/dataframe

np.int64(0)

In [59]:
df[df.duplicated()]

Empty DataFrame
Columns: [Petrol_tax, Average_income, Paved_Highways, Population_Driver_licence(%), Petrol_Consumption]
Index: []

In [62]:
df.drop_duplicates(keep='first',inplace=True)  # delete 2nd duplicate value if there is

# Drop()

In [63]:
df.head()

,Petrol_tax,Average_income,Paved_Highways,Population_Driver_licence(%),Petrol_Consumption
0,9.0,3571,1976,0.525,541
1,9.0,4092,1250,0.572,524
2,9.0,3865,1586,0.580,561
3,7.5,4870,2351,0.529,414
4,8.0,4399,431,0.544,410

In [ ]:
df.drop(index=[0,1,2,3],axis=0) # axis=0 mean delete row and axis=1 mean delete column

In [ ]:
df.drop(index=[0,1,2,3],axis=0,inplace=True) # use inplace=True to delete permanently

In [69]:
df.drop(columns=['Population_Driver_licence(%)'],axis=1,inplace=True) # delete columns

In [71]:
df.shape

(44, 4)

# Group By()

In [9]:
emp = pd.read_csv('ds_salaries.csv')

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L
...,...,...,...,...,...,...,...,...,...,...,...,...
602,602,2022,SE,FT,Data Engineer,154000,USD,154000,US,100,US,M
603,603,2022,SE,FT,Data Engineer,126000,USD,126000,US,100,US,M
604,604,2022,SE,FT,Data Analyst,129000,USD,129000,US,0,US,M
605,605,2022,SE,FT,Data Analyst,150000,USD,150000,US,100,US,M
606,606,2022,MI,FT,AI Scientist,200000,USD,200000,IN,100,US,L

In [11]:
emp['job_title'].value_counts()

job_title
Data Scientist                              143
Data Engineer                               132
Data Analyst                                 97
Machine Learning Engineer                    41
Research Scientist                           16
Data Science Manager                         12
Data Architect                               11
Machine Learning Scientist                    8
Big Data Engineer                             8
Director of Data Science                      7
AI Scientist                                  7
Principal Data Scientist                      7
Data Science Consultant                       7
Data Analytics Manager                        7
BI Data Analyst                               6
Computer Vision Engineer                      6
ML Engineer                                   6
Lead Data Engineer                            6
Applied Data Scientist                        5
Business Data Analyst                         5
Data Engineering Manager                      5
Head of Data                                  5
Data Analytics Engineer                       4
Head of Data Science                          4
Applied Machine Learning Scientist            4
Analytics Engineer                            4
Machine Learning Developer                    3
Data Science Engineer                         3
Lead Data Analyst                             3
Machine Learning Infrastructure Engineer      3
Lead Data Scientist                           3
Principal Data Engineer                       3
Computer Vision Software Engineer             3
Product Data Analyst                          2
ETL Developer                                 2
Cloud Data Engineer                           2
Financial Data Analyst                        2
Director of Data Engineering                  2
Principal Data Analyst                        2
Machine Learning Manager                      1
Marketing Data Analyst                        1
3D Computer Vision Researcher                 1
Finance Data Analyst                          1
Data Specialist                               1
Staff Data Scientist                          1
Big Data Architect                            1
Head of Machine Learning                      1
NLP Engineer                                  1
Lead Machine Learning Engineer                1
Data Analytics Lead                           1
Name: count, dtype: int64

In [19]:
de = emp.groupby('job_title').get_group('Big Data Engineer')

In [20]:
de

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
17,17,2020,SE,FT,Big Data Engineer,100000,EUR,114047,PL,100,GB,S
31,31,2020,EN,FT,Big Data Engineer,70000,USD,70000,US,100,US,L
120,120,2021,MI,FT,Big Data Engineer,60000,USD,60000,ES,50,RO,M
180,180,2021,MI,FT,Big Data Engineer,1672000,INR,22611,IN,0,IN,L
192,192,2021,MI,FT,Big Data Engineer,18000,USD,18000,MD,0,MD,S
213,213,2021,EN,FT,Big Data Engineer,435000,INR,5882,IN,0,CH,L
230,230,2021,EN,FT,Big Data Engineer,1200000,INR,16228,IN,100,IN,L

In [21]:
de.shape

(8, 12)

In [24]:
de['salary'].min()

np.int64(18000)

In [25]:
de['salary'].max()

np.int64(1672000)

In [29]:
de[de['salary']== 18000]

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
192,192,2021,MI,FT,Big Data Engineer,18000,USD,18000,MD,0,MD,S

In [33]:
de['salary'].mean()

np.float64(455000.0)

In [42]:
emp.groupby('job_title').get_group('Data Analytics Manager')['salary'].min()

np.int64(105400)

# Set_Index() and Resert_Index()

In [ ]:
emp.set_index('Unnamed: 0', inplace=True)

In [51]:
emp.reset_index(inplace=True)

In [52]:
emp

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L
...,...,...,...,...,...,...,...,...,...,...,...,...
602,602,2022,SE,FT,Data Engineer,154000,USD,154000,US,100,US,M
603,603,2022,SE,FT,Data Engineer,126000,USD,126000,US,100,US,M
604,604,2022,SE,FT,Data Analyst,129000,USD,129000,US,0,US,M
605,605,2022,SE,FT,Data Analyst,150000,USD,150000,US,100,US,M
606,606,2022,MI,FT,AI Scientist,200000,USD,200000,IN,100,US,L

# Sort_values()

In [54]:
emp['salary'].sort_values()    # assending order

238        4000
185        4000
15         8000
124        8760
196        9272
         ...
285     7000000
137     8500000
102    11000000
7      11000000
177    30400000
Name: salary, Length: 607, dtype: int64

In [55]:
emp['salary'].sort_values(ascending = False)    # Descending order

177    30400000
102    11000000
7      11000000
137     8500000
285     7000000
         ...
196        9272
124        8760
15         8000
238        4000
185        4000
Name: salary, Length: 607, dtype: int64

# apply() and map()

In [56]:
de

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
17,17,2020,SE,FT,Big Data Engineer,100000,EUR,114047,PL,100,GB,S
31,31,2020,EN,FT,Big Data Engineer,70000,USD,70000,US,100,US,L
120,120,2021,MI,FT,Big Data Engineer,60000,USD,60000,ES,50,RO,M
180,180,2021,MI,FT,Big Data Engineer,1672000,INR,22611,IN,0,IN,L
192,192,2021,MI,FT,Big Data Engineer,18000,USD,18000,MD,0,MD,S
213,213,2021,EN,FT,Big Data Engineer,435000,INR,5882,IN,0,CH,L
230,230,2021,EN,FT,Big Data Engineer,1200000,INR,16228,IN,100,IN,L

In [64]:
emp['salary'].apply(lambda x:  f"{round(x/87.20,0)} $")   # this doesn't change data permanently

0       803.0 $
1      2982.0 $
2       975.0 $
3       229.0 $
4      1720.0 $
         ...
602    1766.0 $
603    1445.0 $
604    1479.0 $
605    1720.0 $
606    2294.0 $
Name: salary, Length: 607, dtype: object

In [66]:
emp['salary_in_$'] = emp['salary'].apply(lambda x:  f"{round(x/87.20,0)} $")   # this will add a new coloumn named 'salary_in_$'

In [69]:
emp

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,salary_in_$
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L,803.0 $
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S,2982.0 $
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M,975.0 $
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S,229.0 $
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L,1720.0 $
...,...,...,...,...,...,...,...,...,...,...,...,...,...
602,602,2022,SE,FT,Data Engineer,154000,USD,154000,US,100,US,M,1766.0 $
603,603,2022,SE,FT,Data Engineer,126000,USD,126000,US,100,US,M,1445.0 $
604,604,2022,SE,FT,Data Analyst,129000,USD,129000,US,0,US,M,1479.0 $
605,605,2022,SE,FT,Data Analyst,150000,USD,150000,US,100,US,M,1720.0 $
606,606,2022,MI,FT,AI Scientist,200000,USD,200000,IN,100,US,L,2294.0 $

# to_csv()

- This is used to convert the edited file in any type like dictionaty, list, json and etc and then dump it in i.e save the file

In [70]:
emp.to_csv('Cleaned_emp_data.csv', index=False)

- Here **'cleaned_emp_data.csv'** is the name of our file and **index = False** is to not add new column.

In [ ]:
lst = [5,1,2,3,3,1,2,2,3,6,5,7,8,9,4]
lst2 = []
lst3 = []
for i in lst:
    if lst

In [ ]:
my_lst = [2,2,4,1,6,9,61,61,22]
#Write a Python program to find the second largest element in a list.

In [22]:
my_lst_1 = [10,10,2,2,3,3,4,4,5,7,6,6,6,6]
Given a list of numbers, remove all duplicates without using set()

61

In [25]:
my_lst_1 = [10,10,2,2,3,3,4,4,5,7,6,6,6,6]
lst2 = []
for i in my_lst_1:
    if i not in lst2:
        lst2.append(i)
print(lst2)

[10, 2, 3, 4, 5, 7, 6]

In [ ]:
Reverse a list in-place without using slicing.
[1,2,3,4,5,6]

In [ ]:
n = [2204199]
Count the frequency of each element in a list and display as a dictionary.